### ISSUE TITLE
Plugin isn't picking up the right commit start time on drone 0.5

### ISSUE THREAD

**Issue by cusspvz** [Drillster/drone-email#14]
Used config:

```yaml
pipeline:
  email_notify:
    image: drillster/drone-email
    from: no-reply@email.com
    host: mail.email.com
    username: no-reply@email.com
    password: "123"
    recipients:
      - me@email.com
      - other@email.com
    subject: Resultado do build da branch ${DRONE_COMMIT_BRANCH}
    when:
      branch:
        - branchname
        - otherbranchname
```

Date displayed on all received emails:

<img width="555" alt="captura de ecra 2017-01-24 as 10 43 02" src="https://cloud.githubusercontent.com/assets/3604053/22244064/f08275bc-e221-11e6-96ef-a5748be7efb8.png">
