### ISSUE TITLE
Drone-Email uses wrong mail address

### ISSUE THREAD

**Issue by jacksgt** [Drillster/drone-email#16]
Hi,

I'm trying to set up the drone-email to send notifications after builds, but I'm facing the issue that the plugin is using (or getting?) the wrong email address.

My .drone.yml (snippet):
```yaml
  notify:
    image: drillster/drone-email
    host: smtp.example.com
    port: 587
    username: someone@example.com
    secrets:
      - EMAIL_PASSWORD
    from: drone@example.com
    when:
      status: [ changed, failure ]
```

However, I get the following error message:
```
ime="2017-07-07T06:07:11Z" level=error msg="Could not send email to \"jh@\": gomail: could not send email 1: gomail: invalid address \"jh@\": mail: no angle-addr" 
```
The git comitter mail is very clearly `jackdev at mailbox.org`, so I'm guessing drone-email is using my Gitea user account (`jh`) as the mail address:
```
Branch: ci-mail
Commit: da0b329e
Author: jh

Change mail host
```

Also, despite the error message, the plugins returns with exit code 0.
