### ISSUE TITLE
Notify only on branch "master"

### ISSUE THREAD

**Issue by tobiasKaminsky** [Drillster/drone-email#19]
Hi,
first thanks for your very great plugin 👍 
I want to use it only if a (merge) commit onto master branch is failing.
So I found "when: branch: master", but this seems not to work with this plugin as I always get an email on every failing PR.

```
...
notify:
      image: drillster/drone-email
      host: $EMAIL_HOST
      port: 587
      username: $EMAIL_USERNAME
      password: $EMAIL_PASSWORD
      from: drone@server.com
      recipients_only: true
      recipients: [ $EMAIL_RECIPIENTS ]
      secrets: [ EMAIL_USERNAME, EMAIL_PASSWORD, EMAIL_RECIPIENTS, EMAIL_HOST ]
      when:
        status: failure
        branch: master
...
```

**Comment by mjwwit** [comment]
You can also distinguish between events in Drone, this way you can exclude PRs from triggering the email notification.

This should fix your problem:

```yaml
...
notify:
      image: drillster/drone-email
      host: $EMAIL_HOST
      port: 587
      username: $EMAIL_USERNAME
      password: $EMAIL_PASSWORD
      from: drone@server.com
      recipients_only: true
      recipients: [ $EMAIL_RECIPIENTS ]
      secrets: [ EMAIL_USERNAME, EMAIL_PASSWORD, EMAIL_RECIPIENTS, EMAIL_HOST ]
      when:
        event: push
        status: failure
        branch: master
...
```
