### ISSUE TITLE
Doc does not reflect new syntax

### ISSUE THREAD

**Issue by tobiasKaminsky** [Drillster/drone-email#27]
I am somehow unable to get drone-email working with the new syntax.
To verify my settings, I use this 

```
docker run --rm \
  -e PLUGIN_FROM=email@test.com \
  -e PLUGIN_HOST= \
  -e PLUGIN_USERNAME=email@test.com \
  -e PLUGIN_PASSWORD=secret \
  -e EMAIL_RECIPIENTS=tobias@test.com \
  -e DRONE_REPO_OWNER=repository \
  -e DRONE_REPO_NAME=repo-name \
  -e DRONE_COMMIT_SHA=7fd1a60b01f91b314f59955a4e4d4e80d8edf11d \
  -e DRONE_COMMIT_BRANCH=master \
  -e DRONE_COMMIT_AUTHOR=octocat \
  -e DRONE_COMMIT_AUTHOR_EMAIL=octocat@test.test \
  -e DRONE_BUILD_NUMBER=1 \
  -e DRONE_BUILD_STATUS=success \
  -e DRONE_BUILD_LINK=http://github.com/octocat/hello-world \
  -e DRONE_COMMIT_MESSAGE="Hello world!" \
  -v $(pwd):$(pwd) \
  -w $(pwd) \
  drillster/drone-email

```

I successul receive an email when I execute this locally.

In drone.yml I do have:
```
- name: notify
  image: drillster/drone-email
  host: $EMAIL_HOST
  port: 587
  PLUGIN_FROM: email@test.com
  recipients_only: true
  environment:
    EMAIL_USERNAME:
      from_secret: EMAIL_USERNAME
    EMAIL_PASSWORD:
      from_secret: EMAIL_PASSWORD
    EMAIL_RECIPIENTS:
      from_secret: EMAIL_RECIPIENTS
    EMAIL_HOST:
      from_secret: EMAIL_HOST
  when:
    status:
      - failure
```

I also tested very other different settings, but I always get (on our drone server):
```

time="2019-05-13T11:10:50Z" level=error msg="Could not send email to \"********\": gomail: could not send email 1: gomail: invalid address \"\": mail: no address"
--
2 | gomail: could not send email 1: gomail: invalid address "": mail: no address
```

Locally I tested it with 
```
- name: notify
  image: drillster/drone-email
  from: mail@test.com
  host: smtp.server.com
  when:
    status:
      - failure
```

then I do get 
```
 drone exec                                                                                                              1 ↵
[test:0] + exit 1
[notify:0] time="2019-05-13T12:10:12Z" level=error msg="Error while dialing SMTP server: dial tcp :587: getsockopt: connection refused" 
[notify:1] dial tcp :587: getsockopt: connection refused
2019/05/13 14:10:13 notify : exit code 1
```

I tested above docker command with setting "host=" and I got the same error message.
So locally on "drone exec" it seems that it does not even pick up the host value.

Therefore my fear is that my syntax is wrong.

Can you please have a look and document it in a proper way?

**Comment by dirkhusemann** [comment]
Stumbling over the same symptom: 
```
level=error msg="Error while dialing SMTP server: dial tcp :587: getsockopt: connection refused"
```

**Comment by dirkhusemann** [comment]
@tobiasKaminsky Got it figured out: the configuration has to go under a `settings` header:

```
  - name: notify
    image: drillster/drone-email
    settings:
      recipients_only: true
      recipients:
        - some@some.org
      subject: News from drone!
      host: host.some.org
      port: 587
      from: drone@some.org
      username:
        from_secret: mail_user
      password:
        from_secret: mail_password
```
(using secrets stored in the repo settings on drone). That solved the issue for me.
