### ISSUE TITLE
Email Pending

### ISSUE THREAD

**Issue by jessequinn** [Drillster/drone-email#35]
Hi interesting work here,

but with the following yaml i just have `email: pending` nothing else occurs. I tried office365 and gmail.

```
---
kind: pipeline
type: exec
name: site

platform:
  os: linux
  arch: amd64

steps:
  - name: prepare_production
    commands:
      - cp .env.prod.dist .env
    when:
      branch:
        - master

  - name: prepare_development
    commands:
      - cp .env.dev.dist .env
    when:
      branch:
        - develop

  - name: backend
    commands:
      - composer install

  - name: frontend_development
    commands:
      - yarn install
      - yarn run encore dev
    when:
      branch:
        - develop

  - name: frontend_production
    commands:
      - yarn install
      - yarn run encore production
    when:
      branch:
        - master

  - name: deploy_production
    commands:
      - rm -rf /var/www/jessequinn/*
      - rsync -avz --progress --exclude .git/ . /var/www/jessequinn/
      - chown -R www-data:www-data /var/www/jessequinn
      - find /var/www/jessequinn -type d -exec chmod 755 {} \;
      - find /var/www/jessequinn -type f -exec chmod 644 {} \;
    when:
      branch:
        - master

  - name: deploy_development
    commands:
      - rm -rf /var/www/dev/jessequinn/*
      - rsync -avz --progress --exclude .git/ . /var/www/dev/jessequinn/
      - chown -R www-data:www-data /var/www/dev/jessequinn
      - find /var/www/dev/jessequinn -type d -exec chmod 755 {} \;
      - find /var/www/dev/jessequinn -type f -exec chmod 644 {} \;
    when:
      branch:
        - develop

trigger:
  branch:
    - master
    - develop
  event:
    - push
    - pull_request

---
kind: pipeline
type: docker
name: email

steps:
  - name: notify
    image: drillster/drone-email
    secrets: [email_host, email_username, email_password]
    from: jessequinn@gmail.com
    when:
      status:
        - failure
        - success
      branch:
        - develop
      event:
        - push
        - pull_request

depends_on:
  - site

```

Any ideas of what i am doing wrong here?
