### ISSUE TITLE
Body template provided by external links cannot be used

### ISSUE THREAD

**Issue by BigeYoung** [Drillster/drone-email#43]
As mentioned in [DOCS.md#custom-templates](https://github.com/Drillster/drone-email/blob/master/DOCS.md#custom-templates), I tried:
```yaml
pipeline:
  notify:
    image: drillster/drone-email
    from: noreply@github.com
    host: smtp.mailgun.org
    username: octocat
    password: 12345
    subject: >
      [{{ build.status }}]
      {{ repo.owner }}/{{ repo.name }}
      ({{ build.branch }} - {{ truncate build.commit 8 }})
    body: >
      https://git.io/vgvPz
```

I did receive this email. There is only one line of URL link in the body. I think here should be the content?
