### ISSUE TITLE
Error while dialing SMTP server: EOF

### ISSUE THREAD

**Issue by mashirozx** [Drillster/drone-email#64]
```yml
  - name: email notification on complete
    image: mashirozx/drone-email:latest-arm64
    settings:
      host: 
        from_secret: smtp_host
      port:
        from_secret: smtp_port
      username:
        from_secret: smtp_username
      password:
        from_secret: smtp_password
      from.address:
        from_secret: smtp_from_address
      from.name:
        from_secret: smtp_from_name
      subject: >
        {{#success build.status}}
          {{repo.owner}}/{{repo.name}} ({{build.branch}}) arm64 build #{{build.number}} succeeded
        {{else}}
          {{repo.owner}}/{{repo.name}} ({{build.branch}}) arm64 build #{{build.number}} failed
        {{/success}}
      body: >
        {{#success build.status}}
          {{repo.owner}}/{{repo.name}} ({{build.branch}}) arm64 build #{{build.number}} succeeded: {{build.link}}
        {{else}}
          {{repo.owner}}/{{repo.name}} ({{build.branch}}) arm64 build #{{build.number}} failed: {{build.link}}
        {{/success}}
```

ARM64 image build with command:

```bash
docker build -f Dockerfile.armhf -t mashirozx/drone-email:latest-arm64 .
```

<img width="819" alt="image" src="https://user-images.githubusercontent.com/16148054/169570795-d4b7bda0-c286-4b12-847d-f7c302ba5758.png">
