### ISSUE TITLE
Pulling credentials from orgsecret

### ISSUE THREAD

**Issue by smoslinux** [Drillster/drone-email#70]
Hi, I have an issue pulling the credentials added to the organization project. They are rejecting to be set inside username password. Looks like it's only looking at internal settings per project, but I need it globally.

```
- name: Notify DevOps
  image: drillster/drone-email
  settings:
    from.address: xx
    from.name: xx
    recipients: xxx
    recipients_only: true
    host: xx
    username:
      from_secret: xxx_user
    password:
      from_secret: xxx_key
    subject:
```
