### ISSUE TITLE
mail: no address

### ISSUE THREAD

**Issue by JohnsonHuang4396** [Drillster/drone-email#78]
Hi, I got the following error:
```yaml
time="2024-04-28T09:37:31Z" level=error msg="Could not send email to \"username@gmail.com\": gomail: could not send email 1: gomail: invalid address \"\": mail: no address" 
gomail: could not send email 1: gomail: invalid address "": mail: no address
```

with the following Drone step:
```yaml
  - name: back-notify
    pull: if-not-exists
    image: drillster/drone-email
    settings:
      host: smtp.163.com
      port: 465
      subject: 'Drone build: [{{ build.status }}]'
      body: 'Building result: [{{ build.status }}] {{ repo.name }} ({{ repo.branch }}) #{{ build.number }}'
      username: 
         from_secret: EMAIL_USERNAME
      password:
         from_secret: EMAIL_PASSWORD
      recipients_only: true
      recipients: [username@gmail.com]
    depends_on:
      - back-deploy
    when:
      status:
        - success
        - changed
        - failure
```

How can I fix this error?

**Comment by yanhao98** [comment]
```yml
steps:
  - name: notify
    image: 
    settings:
      from.name: Drone CI
      from.address: 
      host: 
      port: 465
      username: 
      password:
        from_secret: email_password
      recipients_only: true
      recipients: drone-build-notify@x.xyz
      attachments:
        - /drone/src/someFile.txt
        # - /drone/src/someFile.html
    when:
      status:
        - failure
        # - success
depends_on:
  - default-1
```
